// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Adhicitta Masran",
            "email": "adhicittamasran@gmail.com"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/comments": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Get all comments",
                "operationId": "get-all-comments",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.CommentResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Post comment",
                "operationId": "post-comment",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "json request body",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PostRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.PostResponse"
                        }
                    }
                }
            }
        },
        "/comments/{commentId}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Update comment",
                "operationId": "update-comment",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "commentId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "json request body",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mygram-api_src_app_comment_handler_request.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mygram-api_src_app_comment_handler_response.UpdateResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Delete comment",
                "operationId": "delete-comment",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "commentId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.Message"
                        }
                    }
                }
            }
        },
        "/photos": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Photo"
                ],
                "summary": "Get all photos",
                "operationId": "get-all-photos",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mygram-api_src_app_photo_handler_response.PhotoResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Photo"
                ],
                "summary": "Post photo",
                "operationId": "post-photo",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "json request body",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mygram-api_src_app_photo_handler_request.Request"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.PostResponse"
                        }
                    }
                }
            }
        },
        "/photos/{photoId}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Photo"
                ],
                "summary": "Update photo",
                "operationId": "update-photo",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "photoId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "json request body",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mygram-api_src_app_photo_handler_request.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mygram-api_src_app_photo_handler_response.UpdateResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Photo"
                ],
                "summary": "Delete photo",
                "operationId": "delete-photo",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "photoId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.Message"
                        }
                    }
                }
            }
        },
        "/socialmedias": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Social Media"
                ],
                "summary": "Get all social medias",
                "operationId": "get-all-social-medias",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.Response"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Social Media"
                ],
                "summary": "Create social media",
                "operationId": "create-social-media",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "json request body",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mygram-api_src_app_socialmedia_handler_request.Request"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.PostResponse"
                        }
                    }
                }
            }
        },
        "/socialmedias/{socialMediaId}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Social Media"
                ],
                "summary": "Update social media",
                "operationId": "update-social-media",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "socialMediaId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "json request body",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mygram-api_src_app_socialmedia_handler_request.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mygram-api_src_app_socialmedia_handler_response.UpdateResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Social Media"
                ],
                "summary": "Delete social media",
                "operationId": "delete-social-media",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "socialMediaId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.Message"
                        }
                    }
                }
            }
        },
        "/users": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update user",
                "operationId": "update-user",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "json request body",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mygram-api_src_app_user_handler_request.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mygram-api_src_app_user_handler_response.UpdateResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete user account",
                "operationId": "delete-user",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.Message"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Login user",
                "operationId": "login-user",
                "parameters": [
                    {
                        "description": "json request body",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.LoginResponse"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Register user account",
                "operationId": "register-user",
                "parameters": [
                    {
                        "description": "json request body",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.RegisterResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "mygram-api_src_app_comment_handler_request.UpdateRequest": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string",
                    "example": "example"
                }
            }
        },
        "mygram-api_src_app_comment_handler_response.PhotoResponse": {
            "type": "object",
            "properties": {
                "caption": {
                    "type": "string",
                    "example": "no caption"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "photo_url": {
                    "type": "string",
                    "example": "/example"
                },
                "title": {
                    "type": "string",
                    "example": "holiday"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "mygram-api_src_app_comment_handler_response.UpdateResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "message": {
                    "type": "string",
                    "example": "wow"
                },
                "photo_id": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "string",
                    "example": "2022-10-07T15:54:24.575005+07:00"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "mygram-api_src_app_photo_handler_request.Request": {
            "type": "object",
            "required": [
                "photo_url",
                "title"
            ],
            "properties": {
                "caption": {
                    "type": "string",
                    "example": "no caption"
                },
                "photo_url": {
                    "type": "string",
                    "example": "/example"
                },
                "title": {
                    "type": "string",
                    "example": "holiday"
                }
            }
        },
        "mygram-api_src_app_photo_handler_response.PhotoResponse": {
            "type": "object",
            "properties": {
                "User": {
                    "$ref": "#/definitions/response.UserResponse"
                },
                "caption": {
                    "type": "string",
                    "example": "no caption"
                },
                "created_at": {
                    "type": "string",
                    "example": "2022-10-07T15:54:24.575005+07:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "photo_url": {
                    "type": "string",
                    "example": "/example"
                },
                "title": {
                    "type": "string",
                    "example": "holiday"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2022-10-07T15:54:24.575005+07:00"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "mygram-api_src_app_photo_handler_response.UpdateResponse": {
            "type": "object",
            "properties": {
                "caption": {
                    "type": "string",
                    "example": "no caption"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "photo_url": {
                    "type": "string",
                    "example": "/example"
                },
                "title": {
                    "type": "string",
                    "example": "holiday"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2022-10-07T15:54:24.575005+07:00"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "mygram-api_src_app_socialmedia_handler_request.Request": {
            "type": "object",
            "required": [
                "name",
                "social_media_url"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "example"
                },
                "social_media_url": {
                    "type": "string",
                    "example": "/example"
                }
            }
        },
        "mygram-api_src_app_socialmedia_handler_response.UpdateResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "example"
                },
                "social_media_url": {
                    "type": "string",
                    "example": "/example"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2022-10-07T15:54:24.575005+07:00"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "mygram-api_src_app_user_handler_request.UpdateRequest": {
            "type": "object",
            "required": [
                "email",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "example@gmail.com"
                },
                "username": {
                    "type": "string",
                    "example": "example"
                }
            }
        },
        "mygram-api_src_app_user_handler_response.UpdateResponse": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 19
                },
                "email": {
                    "type": "string",
                    "example": "example@gmail.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "string",
                    "example": "2022-10-07T15:54:24.575005+07:00"
                },
                "username": {
                    "type": "string",
                    "example": "example"
                }
            }
        },
        "request.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "example@gmail.com"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "request.PostRequest": {
            "type": "object",
            "required": [
                "message",
                "photo_id"
            ],
            "properties": {
                "message": {
                    "type": "string",
                    "example": "example"
                },
                "photo_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "request.RegisterRequest": {
            "type": "object",
            "required": [
                "age",
                "email",
                "password",
                "username"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "minimum": 9,
                    "example": 19
                },
                "email": {
                    "type": "string",
                    "example": "example@gmail.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "example"
                }
            }
        },
        "response.CommentResponse": {
            "type": "object",
            "properties": {
                "Photo": {
                    "$ref": "#/definitions/mygram-api_src_app_comment_handler_response.PhotoResponse"
                },
                "User": {
                    "$ref": "#/definitions/response.UserResponse"
                },
                "created_at": {
                    "type": "string",
                    "example": "2022-10-07T15:54:24.575005+07:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "message": {
                    "type": "string",
                    "example": "wow"
                },
                "photo_id": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "string",
                    "example": "2022-10-07T15:54:24.575005+07:00"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "response.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                }
            }
        },
        "response.PostResponse": {
            "type": "object",
            "properties": {
                "caption": {
                    "type": "string",
                    "example": "no caption"
                },
                "created_at": {
                    "type": "string",
                    "example": "2022-10-07T15:54:24.575005+07:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "photo_url": {
                    "type": "string",
                    "example": "/example"
                },
                "title": {
                    "type": "string",
                    "example": "holiday"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "response.RegisterResponse": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 19
                },
                "email": {
                    "type": "string",
                    "example": "example@gmail.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "example"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "social_medias": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.SocialMediaResponse"
                    }
                }
            }
        },
        "response.SocialMediaResponse": {
            "type": "object",
            "properties": {
                "User": {
                    "$ref": "#/definitions/response.UserResponse"
                },
                "created_at": {
                    "type": "string",
                    "example": "2022-10-07T15:54:24.575005+07:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "example"
                },
                "social_media_url": {
                    "type": "string",
                    "example": "/example"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2022-10-07T15:54:24.575005+07:00"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "response.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "example@gmail.com"
                },
                "username": {
                    "type": "string",
                    "example": "example"
                }
            }
        },
        "structs.Message": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Your {feature} has been successfully deleted"
                }
            }
        }
    },
    "tags": [
        {
            "name": "User"
        },
        {
            "name": "Photo"
        },
        {
            "name": "Comment"
        },
        {
            "name": "Social Media"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
